apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: default # Update if using a custom namespace
  labels:
    app: redis
spec:
  type: { { .Values.redis.service.type } }
  selector:
    app: redis
  ports:
    - port: { { .Values.redis.service.port } }
      targetPort: { { .Values.redis.service.port } }
